### ISSUE TITLE
Symbol lookup error with vim-xkbswitch

### ISSUE THREAD

**Issue by zoresvit** [ierton/xkb-switch#12]
With last updates to `xkbswitch` the [vim-xkbswitch](https://github.com/lyokha/vim-xkbswitch) plugin crashes with the following error:

```
vim: symbol lookup error: /usr/local/lib/libxkbswitch.so: undefined symbol: _ZN2kb6parse2ERKSsRKSt6vectorISsSaISsEE
```

Also, is it still true that you are going to stop maintaining this project?

**Comment by zoresvit** [comment]
[This commit](https://github.com/ierton/xkb-switch/commit/786daa5818f1ec091e57dd82eb2952862289b3d8) causes the problem.

**Comment by ierton** [comment]
Oh, I forgot to fix the library. Now it should be OK, sorry.
I was sure I am going to stop maintaining the project, but several days ago
Andrey pushed changes which give me an idea how to deal with modern X
server setups. I am going to try and fix the tool.

Regards,
Sergey

2016-02-27 1:32 GMT+03:00 Ruslan Kiianchuk <notifications@github.com>:

**Comment by zoresvit** [comment]
:+1: 

However now another symbol is missing: :)

```
vim: symbol lookup error: /usr/local/lib/libxkbswitch.so: undefined symbol: XkbRF_GetNamesProp
```

**Comment by ierton** [comment]
OK. Sorry again. I used old library for checking, the result was
false-positive. Last commit should fix the issue. I've added ./vimtest.sh
script allowing users to check VIM compatibility.

2016-02-28 5:42 GMT+03:00 Ruslan Kiianchuk <notifications@github.com>:

**Comment by zoresvit** [comment]
Perfect! Thanks a lot for the prompt response and fix!
