### ISSUE TITLE
xkb-switch doesn't show keyboard variant anymore

### ISSUE THREAD

**Issue by realcomplex** [ierton/xkb-switch#14]
Hey!

I recently upgraded from version `20150826-3` to version `20150826-4` of xkb-switch via the Arch User Repository (the `xkb-switch-git` package), and some behaviour has changed in an unexpected way. In particular, xkb-switch doesn't seem to output the keyboard layout variant anymore.

Before the update, calling `xkb-switch` with no arguments would output `us` or `us(intl)` depending on which layout I was using. Now, `xkb-switch` outputs just `us` regardless of what layout I'm actually using at the moment. I just want to use xkb-switch to tell me the current layout variant, I don't actually use it to change the layout.

For reference, here is my xorg keyboard configuration:
```
Section "InputClass"
        Identifier "system-keyboard"
        MatchIsKeyboard "on"
        Option "XkbLayout" "us,us"
        Option "XkbVariant" ",intl"
        Option "XkbOptions" "ctrl:nocaps, grp:alt_shift_toggle"
EndSection
```

Is there any way of getting xkb-switch to output the current layout variant again?

Thanks in advance for the help!

**Comment by grwlf** [comment]
Hi. I can't reproduce this. May be misconfiguration? Notice `Option "XkbLayout" "us,us"` - double us.

**Comment by grwlf** [comment]
Ah, OK. I just read your post more carefully

**Comment by grwlf** [comment]
Could you please check the recent master?

**Comment by realcomplex** [comment]
The latest master branch works exactly like I hoped for! Thank you.
