### ISSUE TITLE
xkb-switch not switching with gnome 3.20

### ISSUE THREAD

**Issue by iago-lito** [ierton/xkb-switch#15]
After a fresh install of Debian 9 (stretch), with Gnome 3.20, `xkb-switch` compiles and seems to run fine, but it actually does nothing:

```
$ xkb-switch 
'us(dvp)'
$ xkb-switch -s 'fr(bepo)'
$ xkb-switch 
'us(dvp)'
$ xkb-switch -n
$ xkb-switch 
'us(dvp)'
```

Here are two interesting outputs:

```
$ cat /etc/default/keyboard
XKBLAYOUT=us,fr,fr
XKBVARIANT=dvp,bepo,oss
BACKSPACE=guess

$ xkb-switch -l
us(dvp)
fr(bepo)
fr(latin9)
fr(oss)
```

.. are they not unconsistent? Could it cause a crash? Any idea what may be going wrong? It used to work just fine with Debian 8 (jessie) and Gnome 3.14.

**Comment by RGBD** [comment]
I believe it's Gnome 3 itself causing problem.
xkb-switch __IS__ changing the layout, but gnome would change it back almost instantly.
Here is my output:
```
$ xkb-switch -l
us
ru
us
```
So if I run the following code multiple times, on rare occasions I will get:
```
$ xkb-switch -s ru && xkb-switch
ru
```
On the same system with xfce4 xkb-switch works perfectly well.

**Comment by iago-lito** [comment]
No news about it so far. Maybe you could crosslink and reference this issue from the Arch forum as well?

I ended up using `setxkbmap`, which does work but which I find more rigid. In particular, once the layout has been set with a `setxkbmap` command, I cannot change it with Gnome shortcuts anymore..

**Comment by iago-lito** [comment]
Hmm, even with:

    $ gsettings get org.gnome.settings-daemon.plugins.keyboard active
    false

    $ gsettings get org.gnome.desktop.input-sources sources
    [('xkb', 'us+dvp'), ('xkb', 'fr+bepo'), ('xkb', 'fr+oss')]

    $ gsettings get org.gnome.desktop.input-sources xkb-options
    ['grp_led:scroll']

..and a reboot, I still get the same problem. Do you think it is enough to get these "other tools disabled" ?

**Comment by RGBD** [comment]
This [answer](https://unix.stackexchange.com/questions/316998/how-to-change-keyboard-layout-in-gnome-3-from-command-line) to my questions seem most helpful.
I don't think it will be posslible to make gnome 3 play nicely with xkb-switch without patching gnome itself.
https://mail.gnome.org/archives/commits-list/2014-September/msg03856.html

**Comment by ierton** [comment]
Sad to see the gnome problem. Unfortunately, I am the opposite to the gnome expert, I haven't got this DE on my machines. Still, I'll happily accept patches if one finds the way to solve the issue.
