### ISSUE TITLE
Libcalls failing when xkb-switch is compiled with `-O2` flag

### ISSUE THREAD

**Issue by zoresvit** [ierton/xkb-switch#17]
When `xkb-switch` is compiled with `-O2` flag, libcalls from Vim fail to correctly change the layout when going from insert mode back to normal. There are no error messages in Vim during execution.

See [vim-xkbswitch #27](https://github.com/lyokha/vim-xkbswitch/issues/27) for related discussion.

Since the problem is quite vague, here's the screencast that demonstrates the issue: [xkb-switch problems](https://www.dropbox.com/s/oeso2u93yyj2ezr/vim-xkb-switch-cast.mp4?dl=1)

Generally the change of execution behavior with `-O2` indicates of some issues with the source code.

**Comment by lyokha** [comment]
This small patch must fix this (original idea from [here](https://github.com/nonpop/xkblayout-state), see how function ``accomodateGroupXkb()`` is used there after ``XkbLockGroup()``

```diff
diff --git a/XKeyboard.cpp b/XKeyboard.cpp
index e3ce64b..0bbcb9f 100644
--- a/XKeyboard.cpp
+++ b/XKeyboard.cpp
@@ -128,6 +128,7 @@ void XKeyboard::set_group(int groupNum)
 {
   Bool result = XkbLockGroup(_display, _deviceId, groupNum);
   CHECK(result == True);
+  (void) get_group();
 }
```

**Comment by lyokha** [comment]
I would also add this

```diff
diff --git a/XKbSwitchApi.cpp b/XKbSwitchApi.cpp
index 821bfd7..febcc26 100644
--- a/XKbSwitchApi.cpp
+++ b/XKbSwitchApi.cpp
@@ -73,6 +73,7 @@ namespace
             return symNames;
         }
 
+        loaded = true;
         xkb->build_layout(symNames);
         return symNames;
     }
```

to make the code clean, though this does not affect anything because vim's ``libcall()`` dlopens/dlcloses on each call.

@zoresvit, could you update the PR?
