### ISSUE TITLE
Question: Is `xkb-switch -x' option still available?

### ISSUE THREAD

**Issue by gyermolenko** [ierton/xkb-switch#22]
I assume you have removed the `-x` option at some point. 
Still, wanted to clarify, since Readme says: 

> Xkb-switch contains some testing facilities, please include output of `xkb-switch -x' command in the report.

I wanted to use this feature to investigate another issue (possibly not event with xkb-switch, tbh)

p.s. I use version 1.4.0

**Comment by ierton** [comment]
Yes, I removed `-x` since xkb-switch doesn't parse the Xkb mode string anymore. Instead, it attempts to read the same information via Xkblib function. Probably I should mention this fact in the manpage. I'll fix the readme too, thanks. Did you try `setxkbmap -query` or `setxkbmap -print`?  IMHO, it should be the preferred source of Xkb configuration.

**Comment by gyermolenko** [comment]
Thanks for the tip.
I've just tried ` setxkbmap -query` / `setxkbmap -print` - nothing peculiar.

Boiled down my issue to just Chrome. When i switch to russian an press ctrl+t - russian `е` comes up in address bar. Have no idea where it comes from.
Would appreciate any ideas on how to approach that.

**Comment by grwlf** [comment]
Unfortunately, I have little knowledge about this. Just maintaining.

Still, let me suggest the following:
To exclude the possibility of some weird Chrome plugin, you may try `xev` to debug what codes does X send to applications in your system. If it is really russian 'e' than you probably should take some longread regarding kyeboard layout configuration
https://wiki.archlinux.org/index.php/X_KeyBoard_extension
https://www.charvolant.org/doug/xkb/html/index.html

**Comment by gryermolenko** [comment]
Thanks!

**Comment by gyermolenko** [comment]
Thanks!
