### ISSUE TITLE
Not available for Mac?

### ISSUE THREAD

**Issue by vitaly-zdanevich** [ierton/xkb-switch#24]

**Comment by grwlf** [comment]
Unfortunately there is no easy way of installing the tool for Mac. This package totally depends on Xorg server libraries and headers, which may be missing from default MacOS distributions nowadays. I've googled some mentions of this here https://support.apple.com/en-us/HT201341
If I understand it correctly, one could install something, that  would offer Xorg-compatible APIs, and this may work, but this investigation goes beyond my responsibilities. I would be happy to merge a pull-request regarding the topic.
