### ISSUE TITLE
How to send switch layout?

### ISSUE THREAD

**Issue by Mladia** [ierton/xkb-switch#27]
I have some question to the usage
Firstly I set my keyboard layouts through `setxkbmap`
`setxkbmap -layout 'us,de,bg' -variant ' , ,phonetic'`
` setxkbmap -option 'grp:alt_caps_toggle'`
 
Than I call 
`xkb-switch -s "de( )"`

and I can write `switch` and I can switch between `us` and `bg`. When I want, I can quickly call `xkb-switch -s "de( )"` and get it. This is clear.
Is it possible to bind some script to a key, so I can can switch between `en` and `bg` without opening a terminal? It there a better way, than running the `xkb-group.sh`, finding it's pid and writing to stdin?

**Comment by grwlf** [comment]
Hi, Mladia. Popular desktop environments, like KDE, usually allow users to bind keyboard combinations to custom commands. What desktop environment do you use?

**Comment by zvezdochiot** [comment]
xbindkeys?

**Comment by Mladia** [comment]
Hi, I have not problem binding the script! 

I am now having the following problem
```
xkb-switch on master [$] 
 ✘130 ➜ setxkbmap -layout 'us,de,bg' -variant ' , ,phonetic'

xkb-switch on master [$] 
 ➜ xkb-switch
us( )

xkb-switch on master [$] 
 ➜ echo "switch" | ./xkb-group.sh "us( )" "bg(phonetic)"

xkb-switch on master [$] 
 ➜ xkb-switch                                           
bg(phonetic)

xkb-switch on master [$] 
 ➜ echo "switch" | ./xkb-group.sh "us( )" "bg(phonetic)"
xkb-switch: Invalid argument: )
xkb-switch: layouts: []

```
I can switch from en to bg, but not back around, when I use the same command. Is `xkb-group.sh` meant to only work in one direction?

**Comment by grwlf** [comment]
Could you please try `xkb-group.sh` from master?

**Comment by Mladia** [comment]
Hallo, I am not using the tool anymore. My last comment had a minimal scenario, which triggered the problem. You can run the commands and see if the expected behavior is there and close the issue.

**Comment by grwlf** [comment]
OK, For me it looks like it should work now, so I'm closing the issue
