### ISSUE TITLE
How to enable C++ 11 for correct build?

### ISSUE THREAD

**Issue by alexandersolovyov** [ierton/xkb-switch#34]
How can I enable C++ 11 support for build? Is there a working version of commands `cmake` and/or `make` commands with options? I am trying to make RPM package for Rosa Linux R8, using cmake v3.5.2 and gcc v4.9.4. It seems, the simplest way is to edit CMakeLists.txt:
change `CMAKE_MINIMUM_REQUIRED(VERSION 2.6)` to version 3.1, and add a string (that works only for cmake 3.1 and higher) after project's name and version definition

~~~cmake
set(CMAKE_CXX_STANDARD 11)
~~~

**Comment by zvezdochiot** [comment]
@alexandersolovyov say> edit CMakeLists.txt

После того, как введено использование типа ```auto``` : https://github.com/ierton/xkb-switch/commit/514e42bfef54fd1e181e29d2d42bb1688b3462ee , я перестал доверять https://github.com/ierton/xkb-switch

См. альтернативы:
* https://github.com/X11-good-tools/xkblayout-state
* https://github.com/X11-good-tools/xkblang

**Comment by grwlf** [comment]
> @alexandersolovyov say> edit CMakeLists.txt
> 
> После того, как введено использование типа `auto` : [514e42b](https://github.com/ierton/xkb-switch/commit/514e42bfef54fd1e181e29d2d42bb1688b3462ee) , я перестал доверять https://github.com/ierton/xkb-switch
> 
> См. альтернативы:
> 
> * https://github.com/X11-good-tools/xkblayout-state
> * https://github.com/X11-good-tools/xkblang

Please use English here

**Comment by grwlf** [comment]
> How can I enable C++ 11 support for build? Is there a working version of commands `cmake` and/or `make` commands with options? I am trying to make RPM package for Rosa Linux R8, using cmake v3.5.2 and gcc v4.9.4. It seems, the simplest way is to edit CMakeLists.txt:
> change `CMAKE_MINIMUM_REQUIRED(VERSION 2.6)` to version 3.1, and add a string (that works only for cmake 3.1 and higher) after project's name and version definition
> 
> ```cmake
> set(CMAKE_CXX_STANDARD 11)
> ```

Looks like C++11 is really not needed in this project so I'm attempting to get rid of it. Could you please re-try the packaging with HEAD (v1.5.1)?

**Comment by grwlf** [comment]
* 1.5.3

**Comment by alexandersolovyov** [comment]
Now compiling without switching to С++ 11. Good, issue closed.

**Comment by alexandersolovyov** [comment]
Didn't check 1.5.1. It worked when I tried version 1.5.3.
