### ISSUE TITLE
Error compilling 'XKeyboard.cpp': istringstream '=' operator is 'deleted'

### ISSUE THREAD

**Issue by alexandersolovyov** [ierton/xkb-switch#35]
I have an error when compiling `XKeyboard.cpp` file, using gcc compiler with option `-std=gnu++11`. It says that '=' operator for `istringstream` is deleted. From [documentation](http://www.cplusplus.com/reference/sstream/istringstream/operator=/), it seems that Copy operator is deleted. Maybe it's better to use `stringstream` with operator `<<` instead?

**Comment by grwlf** [comment]
I removed this code, should be more idiomatic now.

**Comment by alexandersolovyov** [comment]
It looks better. But why not cleaning 'vdr' now? May there be a memory leak?

**Comment by alexandersolovyov** [comment]
Sorry for mixing things up. Maybe it's better to open new issue for 'cleaning up pointers inside vdr is deleted with v1.5.1'?

**Comment by zvezdochiot** [comment]
@alexandersolovyov say> May there be a memory leak?

```
$ cppcheck -f -v . 2>cppcheck.log >/dev/null
$ wc -l cppcheck.log 
0 cppcheck.log

$ splint -preproc *.[ch]*
Splint 3.1.2 --- 20 Feb 2009

Command Line: Unrecognized file extension:
                 XKbSwitchApi.cpp (assuming .cpp is C source code)
  warn when command line file does not have a recognized extension (Use
  -fileextensions to inhibit warning)
Command Line: Unrecognized file extension:
                 XKbSwitch.cpp (assuming .cpp is C source code)
Command Line: Unrecognized file extension:
                 XKeyboard.cpp (assuming .cpp is C source code)
X11Exception.h:37:19: Parse Error: Non-function declaration: class :
                 int. (For help on parse errors, see splint -help parseerrors.)
*** Cannot continue.

$ head -n 37 X11Exception.h | tail -n 1
class X11Exception : public std::exception
```

**Comment by alexandersolovyov** [comment]
Zvezdochuot, I am new in C++. Thanks for this 'cppcheck' command, I will play with it later. You were right, this project now looks like not very reliable...

**Comment by grwlf** [comment]
¯\_(ツ)_/¯
