### ISSUE TITLE
ibus keylayouts ignored

### ISSUE THREAD

**Issue by benibela** [ierton/xkb-switch#9]
Nowadays you can define additional keyboard layouts in ibus:  ![screenshot - 01072016 - 05 34 31 pm](https://cloud.githubusercontent.com/assets/1205129/12175717/0f286526-b564-11e5-88df-029ba69179da.png)

xkb-switch ignores those and can only list the non-ibus layouts (de(nodeadkeys) and us(altgr-intl) in the example)

**Comment by ierton** [comment]
Hi! Unfortunately, I'll stop maintaining this tool. 
xkb-switch works by obtaining xkb token string https://github.com/ierton/xkb-switch/blob/master/XKeyboard.cpp#L72 and parsing it by parse3 https://github.com/ierton/xkb-switch/blob/master/XKeyboard.cpp#L235
I suppose it is not the best way to query X about keyboard layouts and somebody should re-write this part by using better source of information.

If ibus layouts is present in this string (check it with `xkb-switch -x`) than it should  be possible to tweak parse3 function to support them.

**Comment by benibela** [comment]
>If ibus layouts is present in this string (check it with xkb-switch -x

They are not there

**Comment by grwlf** [comment]
Then I don't know easy ways to fix it. One have to find how to query ibus about its layouts.

**Comment by ierton** [comment]
Hi, @benibela . Could you please re-test the application from master? Recent changes in code may fix your issue.

**Comment by benibela** [comment]
No improvement

Although, now ibus seems to be completely broken in all application. Changing the layout there has no effect whatsoever

**Comment by grwlf** [comment]
Closing for now

**Comment by spirobel** [comment]
ibus supports  `setxkbmap -layout us` to switch between layouts. 
amazing :+1:
